[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "markitup-mcp"
dynamic = ["version"]
description = 'An MCP server for the "markitup" library.'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Adam Fourney", email = "adamfo@microsoft.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "mcp~=1.5.0",
  "markitup[all]>=0.1.1,<0.2.0",
]

[project.urls]
Documentation = "https://github.com/microsoft/markitup#readme"
Issues = "https://github.com/microsoft/markitup/issues"
Source = "https://github.com/microsoft/markitup"

[tool.hatch.version]
path = "src/markitup_mcp/__about__.py"

[project.scripts]
markitup-mcp = "markitup_mcp.__main__:main"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/markitup_mcp tests}"

[tool.coverage.run]
source_pkgs = ["markitup-mcp", "tests"]
branch = true
parallel = true
omit = [
  "src/markitup_mcp/__about__.py",
]

[tool.coverage.paths]
markitup-mcp = ["src/markitup_mcp", "*/markitup-mcp/src/markitup_mcp"]
tests = ["tests", "*/markitup-mcp/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.hatch.build.targets.sdist]
only-include = ["src/markitup_mcp"]
